### ISSUE TITLE
python-gnupg needs passphrase

### ISSUE THREAD

**Issue by Imbernix** [blag/django-secure-mail#7] opened 2020-04-11 20:23 UTC
`python manage.py email_signing_key --generate`
does not seem to work unless you add 
`"Passphrase":"xxxxx"`
to
`SECURE_MAIL_SIGNING_KEY_DATA`
and trying to use 
`python manage.py email_signing_key 7AB59FE794A7AC12EBA87507EF33F601153CFE28 --print-private-key `
returns nothing and it writing a script to return the private key I got this error 

> ValueError: For GnuPG >= 2.1, exporting secret keys needs a passphrase to be provided

Maybe, I've missed something in the documentation or not but anyway hopefully this helps someone.

**Comment by Imbernix** [comment] 2020-04-11 22:47
I believe I solved it here 
https://github.com/blag/django-secure-mail/pull/8

**Comment by blag** [comment] 2020-07-23 09:40
I have just pushed out [version 1.2.0](https://pypi.org/project/django-secure-mail/1.2.0) to PyPI, which fixes this issue. Closing. If you find that the issue is not fixed, or if it gets reopened in the future (it shouldn't), comment here and I'll reopen it.

**Closed as completed by blag** 2020-07-23 09:40 UTC
Labels: enhancement, need feedback
